/**
 * One-time migration: converts the legacy Nuxt `contents/` markdown into
 * MDX files under `src/content/` and a generated course index under
 * `src/data/courses.generated.ts`.
 *
 * The legacy `contents/` directory has since been removed — restore it from
 * git history (pre-v2) if this ever needs to be re-run.
 *
 * Usage: node scripts/migrate-content.mjs
 */
import { mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs'
import { basename, join } from 'node:path'
import matter from 'gray-matter'

const ROOT = new URL('..', import.meta.url).pathname
const LEGACY_COURSES = join(ROOT, 'contents/courses')
const LEGACY_NOTES = join(ROOT, 'contents/notes')
const OUT_COURSES = join(ROOT, 'src/content/courses')
const OUT_NOTES = join(ROOT, 'src/content/notes')
const OUT_INDEX = join(ROOT, 'src/data/courses.generated.ts')

mkdirSync(OUT_COURSES, { recursive: true })
mkdirSync(OUT_NOTES, { recursive: true })
mkdirSync(join(ROOT, 'src/data'), { recursive: true })

/** Pulls the paragraph under `### Objective` out of the body. */
function extractObjective(body) {
  const match = body.match(
    /###\s*Objectives?\s*\n+([\s\S]*?)(?=\n##[^#]|\n###\s|$)/,
  )
  if (!match) return { objective: '', rest: body }
  const objective = match[1].trim().replace(/\s+/g, ' ')
  const rest = body.replace(match[0], '').trim()
  return { objective, rest }
}

/** Drops a `## Notes` section whose items are only legacy n-link entries. */
function stripLegacyNotesSection(body) {
  return body.replace(
    /\n##\s*Notes\s*\n([\s\S]*?)(?=\n##\s|$)/,
    (section, inner) => {
      const meaningful = inner
        .split('\n')
        .map((line) => line.trim())
        .filter(
          (line) =>
            line &&
            !/^-\s*<n-link[\s>]/.test(line) &&
            !/^Here (is|are)/i.test(line),
        )
      return meaningful.length === 0 ? '\n' : section
    },
  )
}

/** Rewrites legacy Nuxt/Bootstrap-Vue tags into portable MDX. */
function rewriteLegacyTags(body) {
  return body
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(
      /<n-link to="\/([^"]+)"[^>]*>([\s\S]*?)<\/n-link>/g,
      '[$2](/courses/$1)',
    )
    .replace(/<n-link to="([^"]+)"[^>]*>([\s\S]*?)<\/n-link>/g, '$2')
    .replace(
      /<b-img[^>]*src="([^"]+)"[^>]*alt="([^"]*)"[^>]*\/?>/g,
      '![$2]($1)',
    )
    .replace(/<b-img[^>]*src="([^"]+)"[^>]*\/?>/g, '![]($1)')
    .replace(/"(<=|>=|<|>)"/g, '`$1`')
    .trim()
}

const courses = []
for (const file of readdirSync(LEGACY_COURSES).sort()) {
  if (!file.endsWith('.md')) continue
  const slug = basename(file, '.md')
  const { data, content } = matter(
    readFileSync(join(LEGACY_COURSES, file), 'utf8'),
  )
  const { objective, rest } = extractObjective(content.trim())
  const body = rewriteLegacyTags(stripLegacyNotesSection(rest)).trim()

  const frontmatter = [
    '---',
    `slug: ${slug}`,
    data.code ? `code: ${data.code}` : null,
    `title: ${JSON.stringify(data.title)}`,
    objective ? `objective: ${JSON.stringify(objective)}` : null,
    '---',
  ]
    .filter(Boolean)
    .join('\n')

  writeFileSync(join(OUT_COURSES, `${slug}.mdx`), `${frontmatter}\n\n${body}\n`)
  courses.push({ slug, code: data.code ?? null, title: data.title, objective })
}

// Legacy notes: contents/notes/<course>/<note>.txt
const notes = []
for (const courseDir of readdirSync(LEGACY_NOTES, { withFileTypes: true })) {
  if (!courseDir.isDirectory()) continue
  for (const file of readdirSync(join(LEGACY_NOTES, courseDir.name)).sort()) {
    const noteSlug = file.replace(/\.(txt|md)$/, '')
    const raw = readFileSync(join(LEGACY_NOTES, courseDir.name, file), 'utf8')
    const title = noteSlug
      .split('-')
      .map((word) => word[0].toUpperCase() + word.slice(1))
      .join(' ')
    const frontmatter = [
      '---',
      `slug: ${noteSlug}`,
      `course: ${courseDir.name}`,
      `title: ${JSON.stringify(title)}`,
      '---',
    ].join('\n')
    writeFileSync(
      join(OUT_NOTES, `${courseDir.name}--${noteSlug}.mdx`),
      `${frontmatter}\n\n${rewriteLegacyTags(raw).trim()}\n`,
    )
    notes.push({ slug: noteSlug, course: courseDir.name, title })
  }
}

const banner =
  '// Generated by scripts/migrate-content.mjs — do not edit by hand.\n' +
  "import type { CourseMeta } from '#/features/courses/types'\n" +
  "import type { NoteMeta } from '#/features/notes/types'\n\n"
const courseIndex = `export const COURSE_INDEX: Array<CourseMeta> = ${JSON.stringify(courses, null, 2)}\n`
const noteIndex = `\nexport const NOTE_INDEX: Array<NoteMeta> = ${JSON.stringify(notes, null, 2)}\n`
writeFileSync(OUT_INDEX, banner + courseIndex + noteIndex)

console.log(`Migrated ${courses.length} courses and ${notes.length} notes.`)
