/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as R404RouteImport } from './routes/404'
import { Route as AboutIndexRouteImport } from './routes/about/index'
import { Route as CollegesIndexRouteImport } from './routes/colleges/index'
import { Route as ContactIndexRouteImport } from './routes/contact/index'
import { Route as ContributeIndexRouteImport } from './routes/contribute/index'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as CoursesSlugRouteRouteImport } from './routes/courses/$slug/route'
import { Route as LinksIndexRouteImport } from './routes/links/index'
import { Route as PrivacyIndexRouteImport } from './routes/privacy/index'
import { Route as ProgramsIndexRouteImport } from './routes/programs/index'
import { Route as ProgramsCodeRouteRouteImport } from './routes/programs/$code/route'
import { Route as TermsIndexRouteImport } from './routes/terms/index'
import { Route as CollegesSlugIndexRouteImport } from './routes/colleges/$slug/index'
import { Route as CoursesSlugIndexRouteImport } from './routes/courses/$slug/index'
import { Route as CoursesSlugOldQuestionsRouteImport } from './routes/courses/$slug/old-questions'
import { Route as CoursesSlugSyllabusRouteImport } from './routes/courses/$slug/syllabus'
import { Route as ProgramsCodeIndexRouteImport } from './routes/programs/$code/index'
import { Route as ProgramsCodeScopeRouteImport } from './routes/programs/$code/scope'
import { Route as ProgramsCodeSubjectsRouteImport } from './routes/programs/$code/subjects'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesIndexRoute = CollegesIndexRouteImport.update({
  id: '/colleges/',
  path: '/colleges/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactIndexRoute = ContactIndexRouteImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeIndexRoute = ContributeIndexRouteImport.update({
  id: '/contribute/',
  path: '/contribute/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugRouteRoute = CoursesSlugRouteRouteImport.update({
  id: '/courses/$slug',
  path: '/courses/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksIndexRoute = LinksIndexRouteImport.update({
  id: '/links/',
  path: '/links/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: '/privacy/',
  path: '/privacy/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsIndexRoute = ProgramsIndexRouteImport.update({
  id: '/programs/',
  path: '/programs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsCodeRouteRoute = ProgramsCodeRouteRouteImport.update({
  id: '/programs/$code',
  path: '/programs/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: '/terms/',
  path: '/terms/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesSlugIndexRoute = CollegesSlugIndexRouteImport.update({
  id: '/colleges/$slug/',
  path: '/colleges/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesSlugIndexRoute = CoursesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesSlugRouteRoute,
} as any)
const CoursesSlugOldQuestionsRoute = CoursesSlugOldQuestionsRouteImport.update({
  id: '/old-questions',
  path: '/old-questions',
  getParentRoute: () => CoursesSlugRouteRoute,
} as any)
const CoursesSlugSyllabusRoute = CoursesSlugSyllabusRouteImport.update({
  id: '/syllabus',
  path: '/syllabus',
  getParentRoute: () => CoursesSlugRouteRoute,
} as any)
const ProgramsCodeIndexRoute = ProgramsCodeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProgramsCodeRouteRoute,
} as any)
const ProgramsCodeScopeRoute = ProgramsCodeScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => ProgramsCodeRouteRoute,
} as any)
const ProgramsCodeSubjectsRoute = ProgramsCodeSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => ProgramsCodeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/courses/$slug': typeof CoursesSlugRouteRouteWithChildren
  '/programs/$code': typeof ProgramsCodeRouteRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/colleges/': typeof CollegesIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/contribute/': typeof ContributeIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/links/': typeof LinksIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/courses/$slug/old-questions': typeof CoursesSlugOldQuestionsRoute
  '/courses/$slug/syllabus': typeof CoursesSlugSyllabusRoute
  '/programs/$code/scope': typeof ProgramsCodeScopeRoute
  '/programs/$code/subjects': typeof ProgramsCodeSubjectsRoute
  '/colleges/$slug/': typeof CollegesSlugIndexRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
  '/programs/$code/': typeof ProgramsCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/about': typeof AboutIndexRoute
  '/colleges': typeof CollegesIndexRoute
  '/contact': typeof ContactIndexRoute
  '/contribute': typeof ContributeIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/links': typeof LinksIndexRoute
  '/privacy': typeof PrivacyIndexRoute
  '/programs': typeof ProgramsIndexRoute
  '/terms': typeof TermsIndexRoute
  '/courses/$slug/old-questions': typeof CoursesSlugOldQuestionsRoute
  '/courses/$slug/syllabus': typeof CoursesSlugSyllabusRoute
  '/programs/$code/scope': typeof ProgramsCodeScopeRoute
  '/programs/$code/subjects': typeof ProgramsCodeSubjectsRoute
  '/colleges/$slug': typeof CollegesSlugIndexRoute
  '/courses/$slug': typeof CoursesSlugIndexRoute
  '/programs/$code': typeof ProgramsCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/courses/$slug': typeof CoursesSlugRouteRouteWithChildren
  '/programs/$code': typeof ProgramsCodeRouteRouteWithChildren
  '/about/': typeof AboutIndexRoute
  '/colleges/': typeof CollegesIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/contribute/': typeof ContributeIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/links/': typeof LinksIndexRoute
  '/privacy/': typeof PrivacyIndexRoute
  '/programs/': typeof ProgramsIndexRoute
  '/terms/': typeof TermsIndexRoute
  '/courses/$slug/old-questions': typeof CoursesSlugOldQuestionsRoute
  '/courses/$slug/syllabus': typeof CoursesSlugSyllabusRoute
  '/programs/$code/scope': typeof ProgramsCodeScopeRoute
  '/programs/$code/subjects': typeof ProgramsCodeSubjectsRoute
  '/colleges/$slug/': typeof CollegesSlugIndexRoute
  '/courses/$slug/': typeof CoursesSlugIndexRoute
  '/programs/$code/': typeof ProgramsCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/courses/$slug'
    | '/programs/$code'
    | '/about/'
    | '/colleges/'
    | '/contact/'
    | '/contribute/'
    | '/courses/'
    | '/links/'
    | '/privacy/'
    | '/programs/'
    | '/terms/'
    | '/courses/$slug/old-questions'
    | '/courses/$slug/syllabus'
    | '/programs/$code/scope'
    | '/programs/$code/subjects'
    | '/colleges/$slug/'
    | '/courses/$slug/'
    | '/programs/$code/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/about'
    | '/colleges'
    | '/contact'
    | '/contribute'
    | '/courses'
    | '/links'
    | '/privacy'
    | '/programs'
    | '/terms'
    | '/courses/$slug/old-questions'
    | '/courses/$slug/syllabus'
    | '/programs/$code/scope'
    | '/programs/$code/subjects'
    | '/colleges/$slug'
    | '/courses/$slug'
    | '/programs/$code'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/courses/$slug'
    | '/programs/$code'
    | '/about/'
    | '/colleges/'
    | '/contact/'
    | '/contribute/'
    | '/courses/'
    | '/links/'
    | '/privacy/'
    | '/programs/'
    | '/terms/'
    | '/courses/$slug/old-questions'
    | '/courses/$slug/syllabus'
    | '/programs/$code/scope'
    | '/programs/$code/subjects'
    | '/colleges/$slug/'
    | '/courses/$slug/'
    | '/programs/$code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  CoursesSlugRouteRoute: typeof CoursesSlugRouteRouteWithChildren
  ProgramsCodeRouteRoute: typeof ProgramsCodeRouteRouteWithChildren
  AboutIndexRoute: typeof AboutIndexRoute
  CollegesIndexRoute: typeof CollegesIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  ContributeIndexRoute: typeof ContributeIndexRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  LinksIndexRoute: typeof LinksIndexRoute
  PrivacyIndexRoute: typeof PrivacyIndexRoute
  ProgramsIndexRoute: typeof ProgramsIndexRoute
  TermsIndexRoute: typeof TermsIndexRoute
  CollegesSlugIndexRoute: typeof CollegesSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/': {
      id: '/colleges/'
      path: '/colleges'
      fullPath: '/colleges/'
      preLoaderRoute: typeof CollegesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact/'
      preLoaderRoute: typeof ContactIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute/': {
      id: '/contribute/'
      path: '/contribute'
      fullPath: '/contribute/'
      preLoaderRoute: typeof ContributeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug': {
      id: '/courses/$slug'
      path: '/courses/$slug'
      fullPath: '/courses/$slug'
      preLoaderRoute: typeof CoursesSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links/': {
      id: '/links/'
      path: '/links'
      fullPath: '/links/'
      preLoaderRoute: typeof LinksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy/': {
      id: '/privacy/'
      path: '/privacy'
      fullPath: '/privacy/'
      preLoaderRoute: typeof PrivacyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/': {
      id: '/programs/'
      path: '/programs'
      fullPath: '/programs/'
      preLoaderRoute: typeof ProgramsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs/$code': {
      id: '/programs/$code'
      path: '/programs/$code'
      fullPath: '/programs/$code'
      preLoaderRoute: typeof ProgramsCodeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms/': {
      id: '/terms/'
      path: '/terms'
      fullPath: '/terms/'
      preLoaderRoute: typeof TermsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges/$slug/': {
      id: '/colleges/$slug/'
      path: '/colleges/$slug'
      fullPath: '/colleges/$slug/'
      preLoaderRoute: typeof CollegesSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$slug/': {
      id: '/courses/$slug/'
      path: '/'
      fullPath: '/courses/$slug/'
      preLoaderRoute: typeof CoursesSlugIndexRouteImport
      parentRoute: typeof CoursesSlugRouteRoute
    }
    '/courses/$slug/old-questions': {
      id: '/courses/$slug/old-questions'
      path: '/old-questions'
      fullPath: '/courses/$slug/old-questions'
      preLoaderRoute: typeof CoursesSlugOldQuestionsRouteImport
      parentRoute: typeof CoursesSlugRouteRoute
    }
    '/courses/$slug/syllabus': {
      id: '/courses/$slug/syllabus'
      path: '/syllabus'
      fullPath: '/courses/$slug/syllabus'
      preLoaderRoute: typeof CoursesSlugSyllabusRouteImport
      parentRoute: typeof CoursesSlugRouteRoute
    }
    '/programs/$code/': {
      id: '/programs/$code/'
      path: '/'
      fullPath: '/programs/$code/'
      preLoaderRoute: typeof ProgramsCodeIndexRouteImport
      parentRoute: typeof ProgramsCodeRouteRoute
    }
    '/programs/$code/scope': {
      id: '/programs/$code/scope'
      path: '/scope'
      fullPath: '/programs/$code/scope'
      preLoaderRoute: typeof ProgramsCodeScopeRouteImport
      parentRoute: typeof ProgramsCodeRouteRoute
    }
    '/programs/$code/subjects': {
      id: '/programs/$code/subjects'
      path: '/subjects'
      fullPath: '/programs/$code/subjects'
      preLoaderRoute: typeof ProgramsCodeSubjectsRouteImport
      parentRoute: typeof ProgramsCodeRouteRoute
    }
  }
}

interface CoursesSlugRouteRouteChildren {
  CoursesSlugOldQuestionsRoute: typeof CoursesSlugOldQuestionsRoute
  CoursesSlugSyllabusRoute: typeof CoursesSlugSyllabusRoute
  CoursesSlugIndexRoute: typeof CoursesSlugIndexRoute
}

const CoursesSlugRouteRouteChildren: CoursesSlugRouteRouteChildren = {
  CoursesSlugOldQuestionsRoute: CoursesSlugOldQuestionsRoute,
  CoursesSlugSyllabusRoute: CoursesSlugSyllabusRoute,
  CoursesSlugIndexRoute: CoursesSlugIndexRoute,
}

const CoursesSlugRouteRouteWithChildren =
  CoursesSlugRouteRoute._addFileChildren(CoursesSlugRouteRouteChildren)

interface ProgramsCodeRouteRouteChildren {
  ProgramsCodeScopeRoute: typeof ProgramsCodeScopeRoute
  ProgramsCodeSubjectsRoute: typeof ProgramsCodeSubjectsRoute
  ProgramsCodeIndexRoute: typeof ProgramsCodeIndexRoute
}

const ProgramsCodeRouteRouteChildren: ProgramsCodeRouteRouteChildren = {
  ProgramsCodeScopeRoute: ProgramsCodeScopeRoute,
  ProgramsCodeSubjectsRoute: ProgramsCodeSubjectsRoute,
  ProgramsCodeIndexRoute: ProgramsCodeIndexRoute,
}

const ProgramsCodeRouteRouteWithChildren =
  ProgramsCodeRouteRoute._addFileChildren(ProgramsCodeRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  CoursesSlugRouteRoute: CoursesSlugRouteRouteWithChildren,
  ProgramsCodeRouteRoute: ProgramsCodeRouteRouteWithChildren,
  AboutIndexRoute: AboutIndexRoute,
  CollegesIndexRoute: CollegesIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  ContributeIndexRoute: ContributeIndexRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  LinksIndexRoute: LinksIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  ProgramsIndexRoute: ProgramsIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
  CollegesSlugIndexRoute: CollegesSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
